"""Collect quality, scorer-validation and generator-feasibility results into tables.

Reads the logged results and writes, each as a .csv (full precision) and a .md (for reading):
  docs/tables/quality_summary    Q<NN>: results/quality/*.json from src/quality/measure.py
  docs/tables/scorer_summary     S<NN>: results/scorers/*.json from src/quality/validate_scorers.py
  docs/tables/generator_summary  G<NN>: results/runs/G*/feasibility.json + samples.jsonl
                                 from scripts/check_generators.py
IDs and run descriptions come from configs/runs.json. The generator table also counts, per model,
outputs that hit the max_new_tokens cap and outputs with foreign script or Arabic presentation forms
(regex counts on samples.jsonl, not judgments).

Usage:
  python -m src.quality.summarize_quality
"""
from __future__ import annotations

import csv
import json
import re
import sys
from pathlib import Path

REGISTRY = Path("configs/runs.json")
QUALITY_DIR = Path("results/quality")
SCORER_DIR = Path("results/scorers")
RUNS_DIR = Path("results/runs")
OUT_DIR = Path("docs/tables")

# Cyrillic, CJK (kana, ideographs, hangul) and Devanagari: scripts no Arabic dialect output should contain.
FOREIGN_SCRIPT = re.compile(r"[Ѐ-ӿऀ-ॿ぀-ヿ一-鿿가-힯]")
# Arabic Presentation Forms A and B: contextual glyphs that should be standard letters.
PRESENTATION_FORMS = re.compile(r"[ﭐ-﷿ﹰ-﻿]")


def load_json(path: Path) -> dict:
    """Read one UTF-8 JSON file."""
    return json.loads(path.read_text(encoding="utf-8"))


def write_table(name: str, rows: list[dict], md_columns: dict[str, str], title: str, intro: list[str],
                notes: list[str] | None = None) -> None:
    """Write rows as <name>.csv (all fields) and <name>.md (the columns in md_columns, renamed)."""
    with open(OUT_DIR / f"{name}.csv", "w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    # Markdown: a header, the generated-file notice, then one table with the chosen columns.
    lines = [f"# {title}", "",
             f"Generated by `python -m src.quality.summarize_quality`. Do not edit by hand. "
             f"Full precision and all fields: `{name}.csv`.", "", *intro, "",
             "| " + " | ".join(md_columns.values()) + " |", "|---" * len(md_columns) + "|"]
    lines += ["| " + " | ".join(cell(r[k]) for k in md_columns) + " |" for r in rows]
    if notes:
        lines += ["", *notes]
    (OUT_DIR / f"{name}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def cell(v: object) -> str:
    """One markdown cell: floats rounded for reading, empty values as a dash."""
    if v is None or v == "":
        return "—"
    if isinstance(v, float):
        return f"{v:.3f}" if abs(v) < 1 else f"{v:.2f}"
    return str(v)


def pct(x: float | None) -> float | None:
    """A 0–1 fraction as a percentage."""
    return None if x is None else round(100 * x, 2)


def quality_rows(registry: dict) -> list[dict]:
    """One row per quality result file; the ID is the file-name prefix or the registry entry."""
    rows = []
    for path in sorted(QUALITY_DIR.glob("*.json")):
        q = load_json(path)
        m = re.match(r"(Q\d+)_", path.stem)
        qid = m.group(1) if m else registry.get("quality_files", {}).get(path.stem, "unassigned")
        fid, lex, emb, dup = q["fidelity"], q["lexical"], q["embedding"], q["duplicates"]
        # Data label: the scored file, plus the sample size when only part of it was scored.
        data = Path(q["data"].replace("\\", "/")).stem + (f" (sample {q['sample']}, seed {q['seed']})" if q.get("sample") else "")
        rows.append({
            "id": qid, "date": q["finished"][:10], "data": data, "n": q["n"],
            "exact_dup_pct": pct(dup["exact_rate"]), "near_dup_pct": pct(dup["near_rate"]),
            "near_dup_vs_d1_pct": pct(dup["near_vs_reference_rate"]),
            "mean_words": lex["mean_words"], "ttr": lex["ttr"], "distinct_2": lex["distinct_2"],
            "self_bleu": lex["self_bleu"], "mtld": lex["mtld"],
            "e5_mean_cos_dist": emb["mean_pairwise_cosine_distance"], "vendi": emb["vendi_score"],
            "did_nadi_top1_pct": pct(fid["did_nadi"]["top1_agreement"]), "did_nadi_n": fid["did_nadi"]["n_scored"],
            "did_madar_top1_pct": pct(fid["did_madar"]["top1_agreement"]), "did_madar_n": fid["did_madar"]["n_scored"],
            "kappa_nadi_vs_target": fid["kappa"]["did_nadi_vs_target"]["kappa"],
            "kappa_madar_vs_target": fid["kappa"]["did_madar_vs_target"]["kappa"],
            "kappa_nadi_vs_madar": fid["kappa"]["did_nadi_vs_did_madar"]["kappa"],
            "aldi_mean": fid["aldi"]["mean"], "git_commit": q["git_commit"][:7], "file": path.name,
        })
    # Q IDs in order, files within an ID by name.
    rows.sort(key=lambda r: (r["id"], r["file"]))
    return rows


def scorer_rows() -> list[dict]:
    """One row per scorer per validation run: DID models get F1/P/R, ALDi its rank correlation."""
    rows = []
    for path in sorted(SCORER_DIR.glob("*.json")):
        s = load_json(path)
        base = {"id": s["run_id"], "data": f"MLADI dev ({s['n_sentences']}, {len(s['dialects_scored'])} dialects)",
                "git_commit": s["git_commit"][:7], "file": path.name}
        # DID scorers: single-label predictions scored against the multi-label human gold.
        for key in ("did_nadi", "did_madar"):
            d = s[key]
            gold = d["top1_in_gold"]
            rows.append({**base, "scorer": d["model"],
                         "top1_macro_f1": d["top1"]["macro"]["f1"], "top1_macro_p": d["top1"]["macro"]["precision"],
                         "top1_macro_r": d["top1"]["macro"]["recall"],
                         "mass03_macro_f1": d["mass>=0.3"]["macro"]["f1"],
                         "mass03_macro_p": d["mass>=0.3"]["macro"]["precision"],
                         "mass03_macro_r": d["mass>=0.3"]["macro"]["recall"],
                         "top1_in_gold": f"{gold['accepted']}/{gold['n_scorable']} = {gold['share_of_scorable']}%",
                         "unscorable": gold["n_unscorable"], "spearman_rho": "", "p_value": ""})
        # ALDi: no labels to match, so only its correlation with the number of valid dialects.
        rows.append({**base, "scorer": s["aldi"]["model"], **{k: "" for k in (
            "top1_macro_f1", "top1_macro_p", "top1_macro_r", "mass03_macro_f1", "mass03_macro_p", "mass03_macro_r",
            "top1_in_gold", "unscorable")}, "spearman_rho": s["aldi"]["spearman_rho"],
            "p_value": f"{s['aldi']['p_value']:.1e}"})
    # Same column order in every row, so the CSV header is stable.
    order = ["id", "data", "scorer", "top1_macro_f1", "top1_macro_p", "top1_macro_r", "mass03_macro_f1",
             "mass03_macro_p", "mass03_macro_r", "top1_in_gold", "unscorable", "spearman_rho", "p_value",
             "git_commit", "file"]
    return [{k: r[k] for k in order} for r in rows]


def generator_rows(registry: dict) -> list[dict]:
    """One row per generator feasibility check, with regex counts over its samples."""
    rows = []
    for folder, member in registry["members"].items():
        feas_path = RUNS_DIR / folder / "feasibility.json"
        if not member["run"].startswith("G") or not feas_path.exists():
            continue
        f = load_json(feas_path)
        # Regex counts over the raw outputs (what the model wrote, before any cleaning).
        samples_path = RUNS_DIR / folder / "samples.jsonl"
        samples = [json.loads(l) for l in samples_path.read_text(encoding="utf-8").splitlines() if l.strip()] \
            if samples_path.exists() else []
        rows.append({
            "id": f"{member['run']}-{member['model']}", "model": f["model"], "status": f["status"],
            "batch_size": f["batch_size"], "peak_vram_reserved_mib": f.get("vram_peak", {}).get("peak_reserved"),
            "load_seconds": f.get("load_seconds"), "tokens_per_second": f.get("tokens_per_second"),
            "n_generated": f.get("n_generated"), "max_new_tokens": f["max_new_tokens"],
            "hit_token_cap": sum(s["new_tokens"] >= f["max_new_tokens"] for s in samples),
            "foreign_script": sum(bool(FOREIGN_SCRIPT.search(s["raw_output"])) for s in samples),
            "presentation_forms": sum(bool(PRESENTATION_FORMS.search(s["raw_output"])) for s in samples),
            "temperature": f["sampling"]["temperature"], "top_p": f["sampling"]["top_p"],
            "top_k": f["sampling"]["top_k"], "seed": f["seed"], "git_commit": f["git_commit"][:7],
            "finished": f["finished"], "folder": folder,
        })
    # Fastest first, as in the original G01 table.
    rows.sort(key=lambda r: (r["id"].split("-")[0], -(r["tokens_per_second"] or 0)))
    return rows


def main() -> None:
    """Build the three tables from the logged results."""
    registry = load_json(REGISTRY)
    runs = registry["runs"]
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    q = quality_rows(registry)
    write_table("quality_summary", q, {
        "id": "ID", "date": "Date", "data": "Data", "n": "n", "exact_dup_pct": "Exact dup %",
        "near_dup_pct": "Near dup %", "ttr": "TTR", "distinct_2": "Distinct-2", "self_bleu": "Self-BLEU",
        "mean_words": "Mean words", "e5_mean_cos_dist": "E5 cos. dist.", "vendi": "Vendi",
        "did_nadi_top1_pct": "DID-nadi top-1 agree %", "did_madar_top1_pct": "DID-madar top-1 agree %",
        "aldi_mean": "ALDi mean", "file": "File"},
        "Quality of data sets (Q)", [f"- **{i}:** {runs.get(i, 'not in configs/runs.json')}"
                                     for i in dict.fromkeys(r["id"] for r in q)] + [
            "- Top-1 agreement: share of texts whose top DID prediction is the dialect they were labelled or "
            "generated for (only texts whose dialect the scorer covers; n per row in the CSV)."],
        ["Set-size-dependent measures (TTR, Self-BLEU, Vendi) are only comparable between rows of the same size: "
         "compare Q02 rows with each other, not with Q01."])

    write_table("scorer_summary", scorer_rows(), {
        "id": "ID", "data": "Data", "scorer": "Scorer", "top1_macro_f1": "Top-1 macro F1",
        "top1_macro_p": "Top-1 macro P", "top1_macro_r": "Top-1 macro R", "mass03_macro_f1": "Mass ≥ 0.3 macro F1",
        "mass03_macro_p": "Mass ≥ 0.3 macro P", "mass03_macro_r": "Mass ≥ 0.3 macro R",
        "top1_in_gold": "Top-1 in gold", "unscorable": "Unscorable", "spearman_rho": "Spearman ρ",
        "p_value": "p", "file": "File"},
        "Scorer validation against human gold (S)", [f"- **{i}:** {runs.get(i, 'not in configs/runs.json')}"
                                                     for i in dict.fromkeys(r["id"] for r in scorer_rows())] + [
            "- Top-1 in gold: the scorer's top country is a valid dialect of the sentence (only sentences whose "
            "top country is one of the dev dialects are scorable).",
            "- ALDi: Spearman correlation with the number of valid dialects per sentence."])

    g = generator_rows(registry)
    write_table("generator_summary", g, {
        "id": "ID", "model": "Hub model", "status": "Status", "peak_vram_reserved_mib": "Peak VRAM (reserved, MiB)",
        "load_seconds": "Load (s)", "tokens_per_second": "Tokens/s", "batch_size": "Batch",
        "n_generated": "Generated", "hit_token_cap": "Hit token cap", "foreign_script": "Foreign script",
        "presentation_forms": "Presentation forms", "folder": "Result folder"},
        "Generator feasibility (G)", [f"- **{i}:** {runs.get(i, 'not in configs/runs.json')}"
                                      for i in dict.fromkeys(r["id"].split("-")[0] for r in g)] + [
            "- Counts are regex counts over `samples.jsonl` (raw outputs), not judgments. Foreign script = "
            "Cyrillic, CJK or Devanagari; presentation forms = Arabic Presentation Forms (U+FB50–FDFF, U+FE70–FEFF).",
            "- Tokens/s are comparable only at the same batch size."])
    print(f"wrote quality_summary, scorer_summary and generator_summary (.csv, .md) to {OUT_DIR}")


if __name__ == "__main__":
    sys.exit(main())
